<!DOCTYPE html>
<html lang='en'>
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class='container'>
    <h2>BigDataServer Public DataSet list</h2>
    <table class='table table-hover table-bordered'>
        <thead>
        <tr>
            <th>DataSet</th>
            <th>Description</th>
        </tr>
        </thead>

        <tbody>
        $dataSetTable$
        </tbody>
    </table>
</div>
</body>
</html>