<tr>
    <td>
        <img src='$thumbnailUrl$'/>
    </td>
    <td>
        <dl class="row">

            <dt class="col-sm-2">
                Tags
            </dt>
            <dd class="col-sm-9">
                $dataSetTags$
            </dd>

            <dt class="col-sm-2">
                Name
            </dt>
            <dd class="col-sm-9">
                $dataSetName$
            </dd>

            <dt class="col-sm-2">
                Description
            </dt>
            <dd class="col-sm-9">
                $dataSetDescription$
            </dd>

            <dt class="col-sm-2">
                Links
            </dt>
            <dd class="col-sm-9">
                <a href='$dataSetUrl$.xml'>XML</a>&nbsp; <a href='$dataSetUrl$.bdv'>BDV</a><br/>
            </dd>

        </dl>
    </td>
</tr>